name: Chatbot Demo

on:
  push:
    branches:
      - main  # or specify your branch name

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up the environment variable for the API key
      - name: Set up API Key
        run: echo "API_KEY=${{ secrets.API_KEY }}" >> $GITHUB_ENV

      # Step 3: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build  # Adjust this if your HTML files are in a different directory
