name: GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5
        with:
          source: ./
          destination: ./_site

      - name: Build with Jekyll
        run: |
          bundle install
          bundle exec jekyll build

      - name: Inject API Key into HTML
        env:
          API_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          sed -i 's|<head>|<head><meta name="api-key" content="'$API_KEY'">|' ./_site/index.html

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          name: github-pages
          path: ./_site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4