name: CI/CD Pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install Dependencies
        run: npm install

      - name: Run Tests
        run: npm test

      - name: Inject API Key into HTML
        env:
          API_KEY: ${{ secrets.SECRET_KEY }}
        run: |
          sed -i 's|<head>|<head><meta name="api-key" content="'$API_KEY'">|' ./index.html

      - name: Deploy
        run: |
          echo "Deploying with API Key"
          # Insert your deployment script here